apiVersion: v1
entries:
  browserkube:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2020-09-28T14:33:33.556934-07:00"
    description: A chart for running the Webrecorder Remote Browser System
    digest: 04f76db99440d30531523c42909909246b231c05607f2639edf865dd63c5cd34
    name: browserkube
    type: application
    urls:
    - https://webrecorder.github.io/browserkube/charts/browserkube-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2020-09-28T14:33:33.556447-07:00"
    description: A chart for running the Webrecorder Remote Browser System
    digest: 19c2bd10ceb6951a2ba1f848bea27edc6276d1278fa13d75f80bdcd1dccfe6ce
    name: browserkube
    type: application
    urls:
    - https://webrecorder.github.io/browserkube/charts/browserkube-0.1.0.tgz
    version: 0.1.0
generated: "2020-09-28T14:33:33.554577-07:00"
