version: '3.3'

services:
    browserkube:
        image: webrecorder/browserkube
        build: ./

    pywb:
        image: webrecorder/browserkube-pywb
        build: ./pywb/

    xvfb:
        image: webrecorder/browserkube-xvfb
        build: ./xvfb
