---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-config

data:
  BROWSER: {{ .Values.browser }}
  ACCESS_PREFIX: {{ .Values.storage.access_prefix }}
  STORAGE_PREFIX: {{ .Values.storage.storage_prefix }}
  PROFILE_URL: "{{ .Values.profile_url | default "" }}"
  JOB_CLEANUP_INTERVAL: "{{ .Values.job_cleanup_interval }}"
  JOB_MAX_DURATION: "{{ .Values.job_max_duration }}"
  VNC: "{{ .Values.vnc | default "" }}"

---
apiVersion: v1
kind: Secret
metadata:
  name: storage-auth
  namespace: browsers
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "{{ .Values.storage.access_key }}"
  AWS_SECRET_ACCESS_KEY: "{{ .Values.storage.secret_key }}"
  AWS_ENDPOINT: "{{ .Values.storage.api_endpoint }}"
  MC_HOST: "https://{{ .Values.storage.access_key }}:{{ .Values.storage.secret_key }}@{{ .Values.profile_api_endpoint }}"
  ACL: "{{ .Values.storage.acl }}"

---
apiVersion: v1
kind: Secret
metadata:
  name: storage-auth
  namespace: default
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "{{ .Values.storage.access_key }}"
  AWS_SECRET_ACCESS_KEY: "{{ .Values.storage.secret_key }}"
  AWS_ENDPOINT: "{{ .Values.storage.api_endpoint }}"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: default
data:
  nginx.conf: |
    worker_processes  1;

    error_log  stderr;
    pid        /var/run/nginx.pid;


    events {
        worker_connections  1024;
    }


    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log /dev/stdout;

        sendfile        on;

        keepalive_timeout  65;

        include ./resolvers/resolvers.conf;

        server {
            listen 80;

            proxy_buffering off;

            proxy_buffers 16 64k;
            proxy_buffer_size 64k;

            root /usr/share/nginx/html;
            index index.html index.htm;
            error_page 500 501 502 503 504 /50x.html;

            merge_slashes off;

            location = /50x.html {
                root /usr/share/nginx/html;
            }

            location /_websockify {
                proxy_pass http://$arg_ip.browsers.svc.cluster.local:$arg_port/websockify;

                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-Real-IP $remote_addr;

                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";

                proxy_read_timeout 3600s;
                proxy_send_timeout 3600s;
            }

            location / {
                proxy_pass http://localhost:8080/;
            }
        }
    }
