---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-env-config
  namespace: {{ .Release.Namespace }}

data:
  BROWSER_NAMESPACE: {{ .Values.browser_namespace | default "browsers" }}
  BROWSER_IMAGE_TEMPL: "oldwebtoday/{0}"

  DEFAULT_BROWSER: {{ .Values.browser_image | default "chrome:84" }}
  IN_CLUSTER: "1"

  JOB_ENV: "/tmp/job-env.yaml"

  JOB_CLEANUP_INTERVAL: "{{ .Values.job_cleanup_interval }}"
  PORT: "{{ or (default false .Values.enable_vnc) (default false .Values.remote_cdp) | ternary 8080 80 }}"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: browser-config
  namespace: {{ .Values.browser_namespace | default "browsers" }}

data:
  BROWSER_HOST: "localhost"
  PROXY_PORT: "8080"
  PROXY_CA_URL: "http://wsgiprox/download/pem"
  PROXY_CA_FILE: "/tmp/proxy-ca.pem"
  CHROME_USER_DATA_DIR: "/tmp/profile"
  EXIT_FILE: "/tmp/out/exit"
 

{{- if .Values.storage }}
---
apiVersion: v1
kind: Secret
metadata:
  name: storage-auth
  namespace: {{ .Values.browser_namespace | default "browsers" }}
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "{{ .Values.storage.access_key }}"
  AWS_SECRET_ACCESS_KEY: "{{ .Values.storage.secret_key }}"
  AWS_ENDPOINT: "{{ .Values.storage.api_endpoint }}"
  MC_HOST: "https://{{ .Values.storage.access_key }}:{{ .Values.storage.secret_key }}@{{ .Values.profile_api_endpoint }}"
  ACL: "{{ .Values.storage.acl }}"

---
apiVersion: v1
kind: Secret
metadata:
  name: storage-auth
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "{{ .Values.storage.access_key }}"
  AWS_SECRET_ACCESS_KEY: "{{ .Values.storage.secret_key }}"
  AWS_ENDPOINT: "{{ .Values.storage.api_endpoint }}"

{{- end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: data-config
  namespace: {{ .Release.Namespace }}
data:
  job-env.yaml: |
    config:
      driver_image: {{ .Values.driver_image | default ""}} 
      pywb_image: {{ .Values.pywb_image | default "webrecorder/browserkube-pywb" }}
      xvfb_image: {{ .Values.xvfb_image | default "webrecorder/browserkube-xvfb" }}
      vnc_image: {{ .Values.vnc_image | default "oldwebtoday/remote-desktop-server:dev" }}

      job_max_duration:  {{ mul .Values.job_max_duration 60}}

      mode: {{ .Values.browser_mode | default "headless" | quote }}

      remote_cdp: {{ .Values.remote_cdp | default false }}

      profile_url: "{{ .Values.profile_url | default "" }}"

      enable_vnc: {{ .Values.enable_vnc | default false }}

      idle_timeout: {{ .Values.idle_timeout | default "" }}

      {{- if .Values.storage }}
      storage_prefix: "{{ .Values.storage.storage_prefix }}"
      {{- end }}


      {{- if .Values.profile_urls }}
      profile_urls:
      {{- range .Values.profile_urls }}
        - match: {{ .match | quote }}
          url: {{ .url | quote }}
      {{- end }}
      {{- end }}


  {{- if or .Values.enable_vnc .Values.remote_cdp }}
  nginx.conf: |
    worker_processes  1;

    error_log  stderr;
    pid        /var/run/nginx.pid;


    events {
        worker_connections  1024;
    }


    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log /dev/stdout;

        sendfile        on;

        keepalive_timeout  65;

        include ./resolvers/resolvers.conf;

        server {
            listen 80;

            proxy_buffering off;

            proxy_buffers 16 64k;
            proxy_buffer_size 64k;

            root /usr/share/nginx/html;
            index index.html index.htm;
            error_page 500 501 502 503 504 /50x.html;

            merge_slashes off;

            location = /50x.html {
                root /usr/share/nginx/html;
            }

            {{- if .Values.remote_cdp }}
            location ~* /cdp/([^/]+)/([^/]+)/(.*) {
                proxy_pass http://service-$1.browsers.svc.cluster.local:$2/$3;

                proxy_set_header Host "localhost";

                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection $http_connection;

                #proxy_read_timeout 3600s;
                #proxy_send_timeout 3600s;
            }
            {{- end }}
 

            {{- if .Values.enable_vnc }}
            location /_websockify {
                #proxy_pass http://$arg_ip:$arg_port/websockify;
                proxy_pass http://$arg_ip.browsers.svc.cluster.local:$arg_port/websockify;

                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-Real-IP $remote_addr;

                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection $http_connection;

                proxy_read_timeout 3600s;
                proxy_send_timeout 3600s;
            }
            {{- end }}

            location / {
                proxy_pass http://localhost:8080/;
            }
        }
    }
    {{ end }}
