collections:
  live: $live

use_js_obj_proxy: true

enable_memento: false

enable_auto_fetch: true

recorder:
  source_coll: live
  #filename_template: archive.warc.gz

proxy:
  enable_banner: false
  enable_wombat: true
  enable_content_rewrite: true
  coll: capture
  recording: true


