---
apiVersion: batch/v1
kind: Job
activeDeadlineSeconds: 600
metadata:
  name: "{{ job_name }}"
  labels:
    userid: "{{ userid }}"
    jobid: "{{ jobid }}"
    index: "{{ index }}"

  annotations:
    userTag: "{{ user_tag }}"
    captureUrl: "{{ url }}"
    accessUrl: "{{ access_url }}"
    storageUrl: "{{ storage_url }}"

spec:
  backoffLimit: 2
  ttlSecondsAfterFinished: 120
  template:
    spec:
      restartPolicy: "Never"
      hostAliases:
        - ip: "127.0.0.1"
          hostnames:
            - "embedserver"

      volumes:
        - name: wacz
          emptyDir: {}

{% if not headless %}
        - name: x11
          emptyDir: {}
{% endif %}

{% if profile_url %}
        - name: profile
          emptyDir: {}

      initContainers:
        - name: init-profile
          image: minio/mc
          env:
            - name: MC_HOST_profile
              valueFrom:
                secretKeyRef:
                  name: storage-auth
                  key: MC_HOST

          command: ['/bin/sh']
          args: ['-c', 'mc cp profile/{{ profile_url }} ./ && tar xvzf $(basename {{ profile_url }}) -C /profile && chown -R 1000:1000 /profile && echo "done"']

          volumeMounts:
            - name: profile
              mountPath: '/profile'
{% endif %}

      containers:

{% if not headless %}
        # xvfb
        - name: xvfb
          image: ikreymer/permaproof-xvfb
          imagePullPolicy: Always
          volumeMounts:
            - name: x11
              mountPath: '/tmp/.X11-unix/'

            - name: wacz
              mountPath: '/tmp/out'

          env:
            - name: EXIT_FILE
              value: "/tmp/out/exit"

{% endif %}

        # browser
        # ==================================
        - name: browser
          image: oldwebtoday/chrome:84
          imagePullPolicy: Always
          env:
            - name: PROXY_HOST
              value: "localhost"

            - name: PROXY_PORT
              value: "8080"

            - name: PROXY_CA_URL
              value: "http://wsgiprox/download/pem"

            - name: PROXY_CA_FILE
              value: "/tmp/proxy-ca.pem"

            - name: CHROME_USER_DATA_DIR
              value: "/tmp/profile"
              #value: "/home/browser/.config/google-chrome"

{% if headless %}
            - name: HEADLESS
              value: "1"
{% else %}
            - name: DISPLAY
              value: ":99"
{% endif %}

            - name: EXIT_FILE
              value: "/tmp/out/exit"

          securityContext:
            capabilities: {'add': ['NET_ADMIN', 'SYS_ADMIN', 'SETUID']}

          resources:
            limits:
              cpu: 500m

            requests:
              cpu: 100m

          volumeMounts:
            - name: wacz
              mountPath: '/tmp/out'

{% if not headless %}
            - name: x11
              mountPath: '/tmp/.X11-unix/'
{% endif %}

{% if profile_url %}
            - name: profile
              mountPath: "/tmp/profile"
              #mountPath: '/home/browser/.config/google-chrome'
{% endif %}

        # pywb
        # ==================================
        - name: pywb
          image: ikreymer/permaproof-pywb
          imagePullPolicy: Always
          env:
            - name: INIT_COLLECTION
              value: "capture"

          resources:
            limits:
              cpu: 200m

            requests:
              cpu: 100m

          volumeMounts:
            - name: wacz
              mountPath: '/tmp/out'

        # driver
        # ==================================
        - name: driver
          image: ikreymer/permaproof-driver
          imagePullPolicy: Always

          resources:
            limits:
              cpu: 100m

            requests:
              cpu: 25m

          volumeMounts:
            - name: wacz
              mountPath: '/tmp/out'

          envFrom:
            - secretRef:
                name: storage-auth

          env:
            - name: BROWSER_HOST
              value: "localhost"

            - name: PROXY_HOST
              value: "localhost"

            - name: PROXY_PORT
              value: "8080"

            - name: EMBED_HOST
              value: "embedserver"

            - name: EMBED_PORT
              value: "80"

            - name: CAPTURE_URL
              value: "{{ url }}"

            - name: UPLOAD_FILENAME
              value: "{{ filename }}"

            - name: EXIT_FILE
              value: "/tmp/out/exit"

{% if not headless %}
            - name: DISABLE_CACHE
              value: "1"
{% endif %}


