---
apiVersion: batch/v1
kind: Job
activeDeadlineSeconds: 600
metadata:
  name: "capture-{{ jobid }}-{{ index }}"
  labels:
    userid: "{{ userid }}"
    jobid: "{{ jobid }}"
    index: "{{ index }}"

  annotations:
    captureUrl: "{{ url }}"
    accessUrl: "{{ access_prefix }}{{ filename }}"
    storageUrl: "{{ storage_prefix }}{{ filename }}"

spec:
  backoffLimit: 4
  ttlSecondsAfterFinished: 120
  template:
    spec:
      restartPolicy: "Never"
      hostAliases:
        - ip: "127.0.0.1"
          hostnames:
            - "embedserver"

      volumes:
        - name: wacz
          emptyDir: {}

      containers:
      - name: browser
        image: oldwebtoday/chrome:84
        imagePullPolicy: Always
        env:
          - name: PROXY_HOST
            value: "localhost"

          - name: PROXY_PORT
            value: "8080"

          - name: PROXY_CA_URL
            value: "http://wsgiprox/download/pem"

          - name: PROXY_CA_FILE
            value: "/tmp/proxy-ca.pem"

          - name: HEADLESS
            value: "1"

          - name: EXIT_FILE
            value: "/tmp/out/exit"

        securityContext:
          capabilities: {'add': ['NET_ADMIN', 'SYS_ADMIN', 'SETUID']}

        resources:
          limits:
            cpu: 300m

          requests:
            cpu: 100m

        volumeMounts:
          - name: wacz
            mountPath: '/tmp/out'

      - name: pywb
        image: ikreymer/permaproof-pywb
        imagePullPolicy: Always
        env:
          - name: INIT_COLLECTION
            value: "capture"

        resources:
          limits:
            cpu: 200m

          requests:
            cpu: 100m

        volumeMounts:
          - name: wacz
            mountPath: '/tmp/out'

      - name: driver
        image: ikreymer/permaproof-driver
        imagePullPolicy: Always

        resources:
          limits:
            cpu: 100m

          requests:
            cpu: 25m

        volumeMounts:
          - name: wacz
            mountPath: '/tmp/out'

        envFrom:
          - secretRef:
              name: upload-auth

        env:
          - name: BROWSER_HOST
            value: "localhost"

          - name: PROXY_HOST
            value: "localhost"

          - name: PROXY_PORT
            value: "8080"

          - name: EMBED_HOST
            value: "embedserver"

          - name: EMBED_PORT
            value: "80"

          - name: CAPTURE_URL
            value: "{{ url }}"

          - name: UPLOAD_FILENAME
            value: "{{ filename }}"

          - name: EXIT_FILE
            value: "/tmp/out/exit"
